name: Update DynX List and Restart Container

on:
  push:
    branches: [ main ]
    paths:
      - 'DynX-AntiBan-list.lst'

jobs:
  update-and-restart:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process DynX List and Update Adguard File
        run: |
          awk -F'\\^' '{print "||"$1"^$dnsrewrite=5.198.178.208"}' DynX-AntiBan-list.lst > AdguardHomeReWrite.txt
          
          if git diff --quiet AdguardHomeReWrite.txt; then
            echo "No changes in AdguardHomeReWrite.txt"
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add AdguardHomeReWrite.txt
            git commit -m "Update AdguardHomeReWrite.txt with latest domains"
            git push
          fi

      - name: SSH & Execute Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            rm -f DynX-AntiBan-list.lst
            wget -q https://github.com/MrDevAnony/DynX-AntiBan-Domains/raw/refs/heads/main/DynX-AntiBan-list.lst
            docker compose restart
            exit