name: Generate DynX List For AdguardHome and NginX and Reload nginx
on:
  push:
    branches:
      - main
    paths:
      - DynX-AntiBan-list.lst

jobs:
  update-and-restart:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:

      - name: Generate DynX List and Update Adguard File for tunnel antiban server
        run: |
          awk -F'\\^' '{print "||"$1"^$dnsrewrite=5.198.178.208"}' DynX-AntiBan-list.lst > AdguardHomeReWrite-Tunnel.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add /other/AdguardHomeReWrite-Tunnel.txt
          git commit -m "Update AdguardHomeReWrite-Tunnel.txt with latest domains"
          git push

      - name: Generate DynX List and Update Adguard File for antiban server
        run: |
          awk -F'\\^' '{print "||"$1"^$dnsrewrite=104.237.250.13"}' DynX-AntiBan-list.lst > AdguardHomeReWrite.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add /other/AdguardHomeReWrite.txt
          git commit -m "Update AdguardHomeReWrite.txt with latest domains"
          git push

      - name: Generate allowed_domains.conf from DynX-AntiBan-list.lst For NginX
        run: |
          echo "map \$ssl_preread_server_name \$allowed_domain {" > allowed_domains.conf
          echo "    default 0.0.0.0:0;" >> allowed_domains.conf
          while IFS= read -r domain; do
            [[ $domain = \#* ]] || [[ -z $domain ]] && continue
            echo "    ~^(.*\.)?$domain \$ssl_preread_server_name;" >> allowed_domains.conf
          done < DynX-AntiBan-list.lst
          echo "}" >> allowed_domains.conf
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add /other/allowed_domains.conf
          git commit -m "Update allowed_domains.conf with latest domains"
          git push

      - name: Update allowed_domains.conf on server and Reload Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '${{ secrets.SERVER_IP }}'
          username: '${{ secrets.SSH_USERNAME }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: '${{ secrets.SSH_PORT || 22 }}'
          script: |
            wget -q https://github.com/MrDevAnony/DynX-AntiBan-Domains/raw/refs/heads/main/other/allowed_domains.conf -O /etc/nginx/allowed_domains.conf
            nginx -t && systemctl reload nginx
            exit